# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: self-hosted
    env:
      PROJECT_ROOT: /opt/project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync code
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.venv' \
            --exclude='*.env' \
            --exclude='media/' \
            --exclude='staticfiles/' \
            ./ "$PROJECT_ROOT/"

      - name: Install/Update Python dependencies
        run: |
          cd "$PROJECT_ROOT"
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrations
        run: |
          cd "$PROJECT_ROOT"
          source .venv/bin/activate
          python manage.py migrate --noinput

      # - name: Collect static files
      #   run: |
      #     cd "$PROJECT_ROOT"
      #     source venv/bin/activate
      #     python manage.py collectstatic --noinput

      - name: Start Django app with systemctl
        run: |
          cd "$PROJECT_ROOT"
          source .venv/bin/activate
          systemctl --user restart myproject
